// AUTO-GENERATED by SpaceTreeVisualizerActionSet — do not edit manually.
// Backend host: {{ STV_HOST }}:{{ STV_PORT }}
#pragma once

#include <atomic>
#include <cstdint>
#include <map>
#include <mutex>
#include <string>
#include <vector>
#include "peano4/datamanagement/CellMarker.h"
#include "tarch/logging/Log.h"

/**
 * STVConnection — static, one per MPI rank.
 *
 * Manages the pool of TCP sockets to the SpaceTreeVisualizer backend, one
 * socket per Peano spacetree.  All send helpers are thread-safe for distinct
 * tree IDs; only the socket-open/close path needs the mutex.
 */
class STVConnection {
public:
  /// Frame type constants (must match backend/src/frameTypes.ts)
  static constexpr uint8_t FRAME_STEP_BEGIN     = 0x01;
  static constexpr uint8_t FRAME_STEP_END       = 0x02;
  static constexpr uint8_t FRAME_CELL_BATCH     = 0x03;
  static constexpr uint8_t FRAME_PAUSE_ACK      = 0x06;
  static constexpr uint8_t FRAME_CONTINUE       = 0x07;
  static constexpr uint8_t FRAME_METADATA_NAMES = 0x08;

  /// Handshake / frame flag bits
  static constexpr uint16_t FLAG_ZLIB          = 0x0001;
  static constexpr uint16_t FLAG_PAUSE_MODE    = 0x0002;
  static constexpr uint16_t FLAG_HAS_CELL_DATA = 0x0004;
  static constexpr uint8_t  FRAME_FLAG_COMPRESSED = 0x01;

  /// Protocol constants
  static constexpr uint32_t MAGIC   = 0x50454E30u;
  static constexpr uint8_t  VERSION = 0x02;
  static constexpr int COMPRESS_THRESHOLD = {{ STV_COMPRESS_THRESHOLD }};

  /**
   * Open the TCP socket for treeId if it is not already open, perform the
   * handshake, and store the fd in _treeSockets.  Safe to call from multiple
   * threads simultaneously (protected by _socketsMutex only during open).
   */
  static void openTreeSocket(int treeId, int mpiRank,
                              const std::string& host, int port,
                              bool hasCellData, bool pauseMode);

  /// Send STEP_BEGIN frame on the socket for treeId.
  static void sendStepBegin(int treeId, int step, double timestamp);

  /// Send STEP_END frame on the socket for treeId.
  static void sendStepEnd(int treeId, int step);

  /**
   * Send a CELL_BATCH frame on the socket for treeId.
   * Compresses the payload with zlib if it exceeds COMPRESS_THRESHOLD bytes
   * and USE_ZLIB is defined.
   */
  static void sendCellBatch(int treeId, const std::vector<uint8_t>& batch);

  /**
   * Append a packed CellRecord to batch.
   * Layout: geometry (32 bytes 3D / 24 bytes 2D) per protocol.md.
   */
  static void appendCellRecord(std::vector<uint8_t>& batch,
                                const peano4::datamanagement::CellMarker& marker);

{% if STV_SEND_CELL_DATA and STV_CELL_DATA_TYPE %}
  /**
   * Append a simulation data section after the geometry record.
   * data points to patch_size^D × (n_unknowns + n_aux) doubles.
   */
  static void appendCellData(std::vector<uint8_t>& batch,
                              const double* data, uint32_t nDoubles);
{% endif %}

  /**
   * Send PAUSE_ACK on all open sockets and then block until a CONTINUE byte
   * arrives on any of them.  Called from unprepareTraversal (once per rank).
   */
  static void sendPauseAckAndWait();

private:
  static std::mutex              _socketsMutex;
  static std::map<int,int>       _treeSockets;   ///< treeId -> socket fd
  static tarch::logging::Log     _log;

  /**
   * Write a complete binary frame to fd.
   * This is the only place where the wire format is assembled.
   */
  static void sendFrame(int fd, uint8_t frameType,
                        const uint8_t* payload, uint32_t payloadLen,
                        bool compress = false);

  /// Write exactly len bytes to fd, retrying on EINTR.
  static void writeAll(int fd, const void* buf, std::size_t len);

  /// Read exactly 1 byte from fd, retrying on EINTR.
  static uint8_t readByte(int fd);

  /// CellMarker flags → protocol bitmask
  static uint16_t cellFlags(const peano4::datamanagement::CellMarker& marker);
};
