// AUTO-GENERATED by SpaceTreeVisualizerActionSet — do not edit manually.
#include "STVConnection.h"

#include <arpa/inet.h>
#include <cerrno>
#include <cstring>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#ifdef USE_ZLIB
#  include <zlib.h>
#endif

// ---------------------------------------------------------------------------
// Static member definitions
// ---------------------------------------------------------------------------

std::mutex              STVConnection::_socketsMutex;
std::map<int,int>       STVConnection::_treeSockets;
tarch::logging::Log     STVConnection::_log("STVConnection");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

void STVConnection::writeAll(int fd, const void* buf, std::size_t len) {
  const auto* p = static_cast<const char*>(buf);
  while (len > 0) {
    ssize_t n = ::write(fd, p, len);
    if (n < 0) {
      if (errno == EINTR) continue;
      logWarning("writeAll", "write() failed: " << strerror(errno));
      return;
    }
    p   += n;
    len -= static_cast<std::size_t>(n);
  }
}

uint8_t STVConnection::readByte(int fd) {
  uint8_t b = 0;
  while (true) {
    ssize_t n = ::read(fd, &b, 1);
    if (n == 1)  return b;
    if (n < 0 && errno == EINTR) continue;
    logWarning("readByte", "read() failed or connection closed");
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Frame serialisation
// ---------------------------------------------------------------------------

void STVConnection::sendFrame(int fd, uint8_t frameType,
                              const uint8_t* payload, uint32_t payloadLen,
                              bool compress) {
  // Protocol frame header: 16 bytes
  // [0]    FRAME_TYPE
  // [1]    FRAME_FLAGS  (bit 0 = COMPRESSED)
  // [2-3]  RESERVED
  // [4-7]  PAYLOAD_LEN
  // [8-11] RAW_LEN
  // [12-15] CRC32 of payload bytes

  uint8_t  frameFlags = 0;
  uint32_t rawLen     = payloadLen;

#ifdef USE_ZLIB
  std::vector<uint8_t> compBuf;
  if (compress && payloadLen > COMPRESS_THRESHOLD) {
    uLongf compLen = compressBound(payloadLen);
    compBuf.resize(compLen);
    if (::compress(compBuf.data(), &compLen, payload, payloadLen) == Z_OK) {
      compBuf.resize(compLen);
      payload    = compBuf.data();
      payloadLen = static_cast<uint32_t>(compLen);
      frameFlags = FRAME_FLAG_COMPRESSED;
    }
  }
#endif

  uint32_t checksum = 0;
#ifdef USE_ZLIB
  checksum = static_cast<uint32_t>(
    ::crc32(0L, reinterpret_cast<const Bytef*>(payload), payloadLen));
#endif

  uint8_t header[16] = {};
  header[0] = frameType;
  header[1] = frameFlags;
  // [2-3] RESERVED = 0
  std::memcpy(header + 4,  &payloadLen, 4);
  std::memcpy(header + 8,  &rawLen,     4);
  std::memcpy(header + 12, &checksum,   4);

  writeAll(fd, header,  sizeof(header));
  if (payloadLen > 0) {
    writeAll(fd, payload, payloadLen);
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

void STVConnection::openTreeSocket(int treeId, int mpiRank,
                                   const std::string& host, int port,
                                   bool hasCellData, bool pauseMode) {
  {
    std::lock_guard<std::mutex> lock(_socketsMutex);
    if (_treeSockets.count(treeId)) return;   // already open
  }

  // Resolve host
  struct addrinfo hints{}, *res = nullptr;
  hints.ai_family   = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  std::string portStr = std::to_string(port);
  int rc = ::getaddrinfo(host.c_str(), portStr.c_str(), &hints, &res);
  if (rc != 0 || res == nullptr) {
    logWarning("openTreeSocket",
               "getaddrinfo failed for " << host << ":" << port
               << " — " << gai_strerror(rc));
    return;
  }

  int fd = ::socket(res->ai_family, res->ai_socktype, res->ai_protocol);
  if (fd < 0) {
    ::freeaddrinfo(res);
    logWarning("openTreeSocket", "socket() failed: " << strerror(errno));
    return;
  }

  if (::connect(fd, res->ai_addr, res->ai_addrlen) != 0) {
    ::close(fd);
    ::freeaddrinfo(res);
    logWarning("openTreeSocket",
               "connect() to " << host << ":" << port
               << " failed: " << strerror(errno));
    return;
  }
  ::freeaddrinfo(res);

  // Handshake: 16-byte request
  uint8_t hs[16] = {};
  uint32_t magic   = MAGIC;
  uint8_t  version = VERSION;
  uint8_t  dims    = static_cast<uint8_t>(DIMENSIONS);
  uint16_t flags   = 0;
  if (hasCellData) flags |= FLAG_HAS_CELL_DATA;
  if (pauseMode)   flags |= FLAG_PAUSE_MODE;
#ifdef USE_ZLIB
  flags |= FLAG_ZLIB;
#endif
  int32_t rank   = static_cast<int32_t>(mpiRank);
  int32_t treeId32 = static_cast<int32_t>(treeId);

  std::memcpy(hs + 0,  &magic,   4);
  hs[4] = version;
  hs[5] = dims;
  std::memcpy(hs + 6,  &flags,   2);
  std::memcpy(hs + 8,  &rank,    4);
  std::memcpy(hs + 12, &treeId32, 4);

  writeAll(fd, hs, sizeof(hs));

  // Expect 1-byte ACK
  uint8_t ack = readByte(fd);
  if (ack != 0x41 /*'A'*/) {
    logWarning("openTreeSocket",
               "Backend rejected connection (ack=0x" << std::hex
               << static_cast<int>(ack) << ")");
    ::close(fd);
    return;
  }

  std::lock_guard<std::mutex> lock(_socketsMutex);
  _treeSockets[treeId] = fd;
  logInfo("openTreeSocket",
          "Tree " << treeId << " connected to " << host << ":" << port);
}

void STVConnection::sendStepBegin(int treeId, int step, double timestamp) {
  int fd = 0;
  {
    std::lock_guard<std::mutex> lock(_socketsMutex);
    auto it = _treeSockets.find(treeId);
    if (it == _treeSockets.end()) return;
    fd = it->second;
  }

  // Payload: int32 step_index (4) + float64 timestamp (8) = 12 bytes
  uint8_t payload[12];
  int32_t s = static_cast<int32_t>(step);
  std::memcpy(payload,     &s,         4);
  std::memcpy(payload + 4, &timestamp, 8);
  sendFrame(fd, FRAME_STEP_BEGIN, payload, sizeof(payload));
}

void STVConnection::sendStepEnd(int treeId, int step) {
  int fd = 0;
  {
    std::lock_guard<std::mutex> lock(_socketsMutex);
    auto it = _treeSockets.find(treeId);
    if (it == _treeSockets.end()) return;
    fd = it->second;
  }

  // Payload: int32 step_index (4 bytes)
  uint8_t payload[4];
  int32_t s = static_cast<int32_t>(step);
  std::memcpy(payload, &s, 4);
  sendFrame(fd, FRAME_STEP_END, payload, sizeof(payload));
}

void STVConnection::sendCellBatch(int treeId,
                                  const std::vector<uint8_t>& batch) {
  if (batch.empty()) return;
  int fd = 0;
  {
    std::lock_guard<std::mutex> lock(_socketsMutex);
    auto it = _treeSockets.find(treeId);
    if (it == _treeSockets.end()) return;
    fd = it->second;
  }
  // Compress when large enough (sendFrame handles the zlib path)
  sendFrame(fd, FRAME_CELL_BATCH, batch.data(),
            static_cast<uint32_t>(batch.size()),
            /*compress=*/true);
}

// ---------------------------------------------------------------------------
// CellRecord packing
// ---------------------------------------------------------------------------

uint16_t STVConnection::cellFlags(
    const peano4::datamanagement::CellMarker& marker) {
  uint16_t f = 0;
  if (marker.hasBeenRefined())                                                      f |= 0x0001;
  if (marker.willBeRefined())                                                        f |= 0x0002;
  if (marker.isLocal())                                                              f |= 0x0004;
  if (marker.isParentLocal())                                                        f |= 0x0008;
  if (marker.flags & peano4::datamanagement::CellMarker::AllVerticesInsideDomain)  f |= 0x0040;
  if (marker.willBeEnclaveCell())                                                    f |= 0x0200;
  if (marker.hasBeenEnclaveCell())                                                   f |= 0x0400;
  return f;
}

void STVConnection::appendCellRecord(
    std::vector<uint8_t>& batch,
    const peano4::datamanagement::CellMarker& marker) {

  auto& c = marker.getX();   // cell centre: tarch::la::Vector<D,double>
  auto& h = marker.getH();   // cell size:   tarch::la::Vector<D,double>
  const int lv = marker.level;
  auto& rp = marker.getRelativePositionWithinFatherCell();
  uint16_t flags = cellFlags(marker);

#if DIMENSIONS == 3
  // 32-byte record
  uint8_t rec[32] = {};
  float cx = static_cast<float>(c[0]);
  float cy = static_cast<float>(c[1]);
  float cz = static_cast<float>(c[2]);
  float hx = static_cast<float>(h[0]);
  float hy = static_cast<float>(h[1]);
  float hz = static_cast<float>(h[2]);
  int16_t level = static_cast<int16_t>(lv);
  int8_t rpx = static_cast<int8_t>(rp[0]);
  int8_t rpy = static_cast<int8_t>(rp[1]);
  int8_t rpz = static_cast<int8_t>(rp[2]);

  std::memcpy(rec +  0, &cx,    4);
  std::memcpy(rec +  4, &cy,    4);
  std::memcpy(rec +  8, &cz,    4);
  std::memcpy(rec + 12, &hx,    4);
  std::memcpy(rec + 16, &hy,    4);
  std::memcpy(rec + 20, &hz,    4);
  std::memcpy(rec + 24, &level, 2);
  std::memcpy(rec + 26, &flags, 2);
  rec[28] = static_cast<uint8_t>(rpx);
  rec[29] = static_cast<uint8_t>(rpy);
  rec[30] = static_cast<uint8_t>(rpz);
  // rec[31] = 0 (pad, already zero-initialised)

  batch.insert(batch.end(), rec, rec + sizeof(rec));
#else
  // 24-byte record (2D)
  uint8_t rec[24] = {};
  float cx = static_cast<float>(c[0]);
  float cy = static_cast<float>(c[1]);
  float hx = static_cast<float>(h[0]);
  float hy = static_cast<float>(h[1]);
  int16_t level = static_cast<int16_t>(lv);
  int8_t rpx = static_cast<int8_t>(rp[0]);
  int8_t rpy = static_cast<int8_t>(rp[1]);

  std::memcpy(rec +  0, &cx,    4);
  std::memcpy(rec +  4, &cy,    4);
  std::memcpy(rec +  8, &hx,    4);
  std::memcpy(rec + 12, &hy,    4);
  std::memcpy(rec + 16, &level, 2);
  std::memcpy(rec + 18, &flags, 2);
  rec[20] = static_cast<uint8_t>(rpx);
  rec[21] = static_cast<uint8_t>(rpy);
  // rec[22-23] = 0 (pad)

  batch.insert(batch.end(), rec, rec + sizeof(rec));
#endif
}

{% if STV_SEND_CELL_DATA and STV_CELL_DATA_TYPE %}
void STVConnection::appendCellData(std::vector<uint8_t>& batch,
                                   const double* data, uint32_t nDoubles) {
  // data_len (4 bytes) + nDoubles × float64 (8 bytes each)
  uint32_t byteCount = nDoubles * sizeof(double);
  uint8_t hdr[4];
  std::memcpy(hdr, &byteCount, 4);
  batch.insert(batch.end(), hdr, hdr + 4);
  const auto* raw = reinterpret_cast<const uint8_t*>(data);
  batch.insert(batch.end(), raw, raw + byteCount);
}
{% endif %}

// ---------------------------------------------------------------------------
// Pause / Resume
// ---------------------------------------------------------------------------

void STVConnection::sendPauseAckAndWait() {
  // Send PAUSE_ACK on all open sockets (one PAUSE_ACK per rank, per protocol)
  // then block until at least one CONTINUE byte arrives.
  std::map<int,int> sockets;
  {
    std::lock_guard<std::mutex> lock(_socketsMutex);
    sockets = _treeSockets;
  }

  for (auto& [treeId, fd] : sockets) {
    sendFrame(fd, FRAME_PAUSE_ACK, nullptr, 0);
  }

  // Block on the first socket's CONTINUE signal.  In practice the backend
  // sends CONTINUE to all sockets simultaneously.
  if (!sockets.empty()) {
    int firstFd = sockets.begin()->second;
    uint8_t b = readByte(firstFd);
    if (b != FRAME_CONTINUE) {
      logWarning("sendPauseAckAndWait",
                 "Unexpected byte while waiting for CONTINUE: 0x"
                 << std::hex << static_cast<int>(b));
    }
  }
}
